[15.0][ADD] project_close_forecast_date
solvosci/slv-project pull request #23
Opened 2024-06-20 06:24 UTC by ChristianSantamaria

Adds new field forecast date in purchase order line.

@dalonsod Can u review this addon?

2024-06-20 08:02 UTC, dalonsod requested changes
See comments. Please pay attention at dependencies, security access and readonly considerations

2024-06-20 08:02 UTC, dalonsod commented on project_close_forecast_date/__manifest__.py
> +    "depends": ["project_purchase"],
This dependency is actually unused (`project_purchase` only adds a soft link between purchases and projects, nothing that seems to be used here), and stock dependency (due to `stock_picking`) is missing, then better try this:
```suggestion
    "depends": ["project", "purchase_stock"],

```

2024-06-20 08:02 UTC, dalonsod commented on project_close_forecast_date/models/project_project.py
> +            order_line_ids = self.env['purchase.order.line'].search([
Have you check every user with project access can read every purchase order line?

2024-06-20 08:02 UTC, dalonsod commented on project_close_forecast_date/models/project_project.py
> +            date = datetime.strptime(vals['last_close_date'], '%Y-%m-%d').date()
we could skip `strptime()` process first calling to `super().write()` and later inspecting `self[0].last_close_date.date()`, is it right?

2024-06-20 08:02 UTC, dalonsod commented on project_close_forecast_date/models/project_project.py
> +        if 'last_close_date' in vals and vals['last_close_date']:
Ouch!!! Please check, but `last_close_date` is a non stardard field for `project.project` module, it's added by another addon, could you check?

2024-06-20 08:02 UTC, dalonsod commented on project_close_forecast_date/models/purchase_order_line.py
> +    forecast_date = fields.Date()
Should this field be readonly/computed, or users can manually change it?

2024-06-20 08:02 UTC, dalonsod commented on project_close_forecast_date/views/purchase_order_views.xml
> +                <field name="forecast_date" />
If this field can be manually set by users, is there any state that should lock it, like other fields? And should it be visible in those cases for every user role?

2024-06-20 08:02 UTC, dalonsod commented on project_close_forecast_date/models/purchase_order.py
> +            self.order_line.forecast_date = self.date_planned.astimezone(tz).date()
This process is repeated below, then should be moved to an order line method, in order to not be repeated. I suspect that there's an Odoo base method that makes such conversion, if I find it, I'll tell you

2024-06-24 10:33 UTC, ChristianSantamaria commented
@dalonsod Updated Test enviroment

2024-06-24 14:57 UTC, dalonsod requested changes
This code still needs some refactoring an adjustments:
* `last_close_date` change in projects and POs security. When I noted that a Project User can't access POLs by default (if it's not a Purchase User as well), I wasn't saying that changing project last close date was a forbidden operation. I simply said that an error would be raised if we don't prevent that situation. I think that such operation should be actually enabled, so an ACL/record rule for POLs should be added or a `sudo()` when reading and writing POLs should be coded. IMO the last one is the right one (no matter who wants to change this date, later operations must be performed).
* UTC code for determining date from datetime is not duplicated, but wrote three times! Please unify it in a single method for e.g. purchase order line.
* Could you check this? When PO `date_planned` changes, every `date_planned` for its POLs are changed too, with this new value. So onchange management seems to be only required at POL level. This should work: making `forecast_date` computed stored. Compute method should only depends on POL `date_planned` field AND linked stock picking `scheduled_date` (so every `onchange` method could be removed, and `write` for picking too).

2024-06-26 06:29 UTC, ChristianSantamaria commented
@dalonsod Updated

2024-06-26 15:26 UTC, dalonsod commented on project_close_forecast_date/models/purchase_order_line.py
> +    @api.depends('date_planned')
If this dependency is added, write() stuff for stock.picking should become unneeded? Please check (when picking is created and when picking is modified):
```suggestion
    @api.depends('date_planned', 'move_ids.picking_id.scheduled_date') 
```

2024-06-28 12:16 UTC, ChristianSantamaria commented
When change "last_close_date" in project update purchase.order.line while order_id.invoice_status != invoiced
@dalonsod can u check?

2024-06-28 12:30 UTC, dalonsod reviewed
See very last comments, I promise!

2024-06-28 12:30 UTC, dalonsod commented on project_close_forecast_date/models/project_project.py
> +                ('order_id.invoice_status', '!=', 'invoiced')
Well.. we might exclude cancelled lines IMO:
```suggestion
                ('order_id.invoice_status', '!=', 'invoiced'),
                ('state', '!=', 'cancel'),
```

2024-06-28 12:30 UTC, dalonsod commented on project_close_forecast_date/models/purchase_order_line.py
> +        tz = timezone(self.env.user.tz or self.company_id.partner_id.tz or 'UTC')
At last, I've found this:

https://github.com/odoo/odoo/blob/6708408c9d2f8137271809962f0d39ee38a0a24b/odoo/fields.py#L1887-L1909

Such function could be called like .e.g. `fields.Date.context_today(self, timestamp=date)`, could you try?

2024-07-01 06:46 UTC, ChristianSantamaria commented
@dalonsod and now?

2024-07-01 06:55 UTC, dalonsod approved these changes
POL `forecast_date` will be initialized with `date_planned`.

:+1:

2024-07-01 06:55 UTC, merged